### ISSUE TITLE
:( fastcgi broke

### ISSUE THREAD

**Issue by johnjelinek** [dcoxall/dcoxall-wordpress#4]
I think 2.0.0 broke FastCGI. When I boot wordpress, I get:

`The page you are looking for is temporarily unavailable.
Please try again later.`

`# cat /var/log/nginx/error.log
2014/02/24 23:23:35 [crit] 5157#0: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.2.2, server: localhost, request: "GET /wp-admin/install.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "localhost:8080"`

**Comment by dcoxall** [comment]
hmm. Do you mind giving me more information about your set-up? The upgrade to 2.0.0 was in large because I found the module barely worked in most situations and also broke the rule that it could be run anytime and would always result in the correct set-up. The previous version relied on many much more complex modules which made managing dependencies a nightmare.

If you could provide some steps as to how to re-produce then I will look into fixing it.

Sorry about that.

**Comment by johnjelinek** [comment]
Are you familiar with Vagrant? I could send you a Vagrantfile with my
setup. In the meantime, I had to revert to 1.0.1 to get my system to work.

**Comment by dcoxall** [comment]
Could you perhaps share your vagrant setup and puppet manifest. The ideal setup is to allow the wordpress module to setup all the dependencies including nginx and php so hasn't been built to handle or unique set-ups of either.
